#!/bin/bash

#PBS -V
#PBS -S /bin/bash
#PBS -N MussicScattering_withLowpass_AllData
#PBS -l nodes=1:ppn=2
#PBS -l walltime=04:00:00
#PBS -l mem=16GB
#PBS -q s48
#PBS -M yss265@nyu.edu
#PBS -m bea
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}


cd /home/yss265/MusicClassification
module load scipy/intel/0.13.3
python signalScattering.py

exit 0;
