#!/bin/bash

#PBS -V
#PBS -S /bin/bash
#PBS -N Run_1_100_0.3
#PBS -l nodes=1:ppn=1
#PBS -l walltime=168:00:00
#PBS -l mem=4GB
#PBS -q s48
#PBS -M yss265@nyu.edu
#PBS -m bea
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}

cd /home/yss265/MusicClassification/finalproject
module load librosa
python workbook.py $n $k $b $nei
exit 0;
